name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: cd app && npm install

      - name: Clean install with npm ci
        run: cd app && npm ci
       
      - name: Build on EAS
        run: cd app && eas build --profile preview --platform ios --non-interactive
